version: "3.9"
services:
  backend:
    build:
      context: ./puppy-classification-backend
      dockerfile: Dockerfile
    command: gunicorn wsgi:app --bind 0.0.0.0:5000
    ports:
      - "5000:5000"
    volumes:
      - ./puppy-classification-backend/:/app
    env_file:
      - ./settings/.env
    networks:
      - app-tier
    depends_on:
      - mysql_db
    restart: always

  frontend:
    build:
      context: ./puppy-classification-frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 3000:3000
    networks:
      - app-tier
    volumes:
      - ./puppy-classification-frontend/:/puppy-classification-frontend
      - build_folder:/puppy-classification-frontend/build
      - ./puppy-classification-frontend/node_modules/:/puppy-classification-frontend/node_modules
    tty: true

  # nginx 컨테이너(서버)
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend
    networks:
      - app-tier

  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    command: rabbitmq-server
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=puppy
      - RABBITMQ_DEFAULT_PASS=puppy
    networks:
      - app-tier
    ports:
      - 5672:5672
      - 15672:15672
    depends_on:
      - backend

  celery:
    build:
      context: ./puppy-classification-backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./settings/.env
    depends_on:
      - "rabbit"
      - "backend"
    networks:
      - app-tier
    command: ["celery", "-A", "tasks", "worker", "--loglevel=info"]
    volumes:
      - ./puppy-classification-backend:/usr/src/app

networks:
  app-tier:
    driver: bridge
# 컨테이너 내려도 데이터 유지되도록 함
volumes:
  build_folder: null
