version: "3.9"
services:
  backend:
    build:
      context: ./puppy-classification-backend
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 app:app
    ports:
      - "5000:5000"
    volumes:
      - ./puppy-classification-backend/:/app
    networks:
      - app-tier
    env_file:
      - ./settings/.env

    restart: always

  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    command: rabbitmq-server
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=puppy
      - RABBITMQ_DEFAULT_PASS=puppy
    networks:
      - app-tier
    ports:
      - 5672:5672
      - 15672:15672
    depends_on:
      - backend

  celery:
    build:
      context: ./puppy-classification-backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./settings/.env
    depends_on:
      - "rabbit"
      - "backend"
    networks:
      - app-tier
    command: ["celery", "-A", "tasks", "worker", "--loglevel=info"]
    volumes:
      - ./puppy-classification-backend:/usr/src/app

networks:
  app-tier:
    driver: bridge
# 컨테이너 내려도 데이터 유지되도록 함
volumes:
  build_folder: null
