version: "3.9"

services:
  #   flask:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   command: gunicorn --bind 0.0.0.0:5000 app:app
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./backend/:/backend/
  #   env_file:
  #     - ./settings/dev/.env.dev
  #   depends_on:
  #     - mysql_db
  #   restart: always

  # mysql_db:
  #   build: ./backend/mysql
  #   image: mysql:8.0.20
  #   container_name: mysql_db
  #   restart: always
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: summer-bootcamp-2022
  #     MYSQL_USER: admin
  #     MYSQL_PASSWORD: siliconvalley
  #   command:
  #     - --character-set-server=utf8mb4
  #     - --collation-server=utf8mb4_unicode_ci

  frontend:
    build:
      context: ./puppy-classification-frontend
      dockerfile: Dockerfile.prod
    container_name: frontend
    command: ["yarn", "start"]
    ports:
      - 80:3000
    volumes:
      - ./puppy-classification-frontend/:/puppy-classification-frontend
      - ./puppy-classification-frontend/node_modules/:/puppy-classification-frontend/node_modules
    environment:
      - CI=true
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BACKEND_URL=http://localhost:8000
    tty: true
