version: "3.9"
services:
  mysql_db:
    platform: linux/amd64
    image: mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./settings/.env.dev

  backend:
  build:
    context: ./puppy-classification-backend
    dockerfile: Dockerfile
  command: gunicorn --bind 0.0.0.0:5000 app:app
  ports:
    - "5000:5000"
  volumes:
    - ./puppy-classification-backend/:/app
  env_file:
    - ./settings/.env
  depends_on:
    - mysql_db
  restart: always

  frontend:
    build:
      context: ./puppy-classification-frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./puppy-classification-frontend/:/puppy-classification-frontend
      - build_folder:/puppy-classification-frontend/build
      - ./puppy-classification-frontend/node_modules/:/puppy-classification-frontend/node_modules
    tty: true

  # nginx 컨테이너(서버)
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend
    networks:
      - app-tier

  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    command: rabbitmq-server
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=localhost
    networks:
      - app-tier
    ports:
      - 5672:5672
      - 15672:15672

    depends_on:
      - backend

  celery:
    build:
      context: ./puppy-classification-backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./settings/.env
    depends_on:
      - "rabbit"
      - "backend"
    networks:
      - app-tier
    command: ["celery", "worker", "-A", "task", "--pool", "--loglevel=info"]
    volumes:
      - ./puppy-classification-backend:/usr/src/app

networks:
  app-tier:
    driver: bridge
# 컨테이너 내려도 데이터 유지되도록 함
volumes:
  build_folder: null
